/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestRoomsRouteImport } from './routes/_guest/rooms'
import { Route as GuestRoomsRoomIdRouteImport } from './routes/_guest/rooms_.$roomId'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoomsRoute = GuestRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRoomsRoomIdRoute = GuestRoomsRoomIdRouteImport.update({
  id: '/rooms_/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms': typeof GuestRoomsRoute
  '/rooms/$roomId': typeof GuestRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms': typeof GuestRoomsRoute
  '/rooms/$roomId': typeof GuestRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/rooms': typeof GuestRoomsRoute
  '/_guest/rooms_/$roomId': typeof GuestRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms' | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms' | '/rooms/$roomId'
  id: '__root__' | '/' | '/_guest' | '/_guest/rooms' | '/_guest/rooms_/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/rooms': {
      id: '/_guest/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof GuestRoomsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/rooms_/$roomId': {
      id: '/_guest/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof GuestRoomsRoomIdRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface GuestRouteChildren {
  GuestRoomsRoute: typeof GuestRoomsRoute
  GuestRoomsRoomIdRoute: typeof GuestRoomsRoomIdRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestRoomsRoute: GuestRoomsRoute,
  GuestRoomsRoomIdRoute: GuestRoomsRoomIdRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
