export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  GUEST_NOT_FOUND: 'GUEST_NOT_FOUND',
  GUEST_DISPLAY_CODE_GENERATION_FAILED: 'GUEST_DISPLAY_CODE_GENERATION_FAILED',

  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_PASSWORD_REQUIRED: 'ROOM_PASSWORD_REQUIRED',
  ROOM_PASSWORD_INVALID: 'ROOM_PASSWORD_INVALID',
  ROOM_HOST_ONLY: 'ROOM_HOST_ONLY',
  ROOM_FULL: 'ROOM_FULL',

  ROOM_PARTICIPANT_NOT_FOUND: 'ROOM_PARTICIPANT_NOT_FOUND',
  ALREADY_JOINED_ROOM: 'ALREADY_JOINED_ROOM',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
